name: 'dependabot-auto-merge'
description: 'Auto-merge Dependabot pull-requests'

inputs:
  github-token:
    description: The GitHub token used to merge the pull-request
    required: true

  config:
    description: Path to configuration file (relative to root)
    default: .github/auto-merge.yml
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
